### ISSUE TITLE
is plugin supported and available?

### ISSUE THREAD

**Issue by imvisiontech** [intelsdi-x/snap-plugin-processor-anomalydetection#6]
Hi,
I could not find this plugin available in the plugin package in version 0.15 beta or in previous versions.
is it fully supported? is it for future support?

**Comment by candysmurf** [comment]
@imvisiontech, I'll check and get back to you.

**Comment by sandlbn** [comment]
@imvisiontech & @candysmurf Plugin was opensourced after release 15. That's why wasn't included in plugin package.

**Comment by candysmurf** [comment]
@sandlbn, thanks!
@imvisiontech, it's confirmed that we'll add it in the next release. Stay tuned. At the meantime, you can always build it from the source. Please let us know if you have any other questions. thanks.

**Comment by kindermoumoute** [comment]
Plugin release: https://github.com/intelsdi-x/snap-plugin-processor-anomalydetection/releases
